[package]
name = "schist-codec-psd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schist-core.workspace = true
schist-compositor.workspace = true
schist-color.workspace = true
schist-psd-descriptor.workspace = true
miniz_oxide.workspace = true
anyhow.workspace = true
byteorder.workspace = true
thiserror.workspace = true
log.workspace = true
