[package]
name = "photoslop-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
photoslop-color.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
serde.workspace = true
log.workspace = true
